
paginate: 10
pygments: true
permalink: none
name: Next Jump Blog
description: The Next Jump blog is a look into the culture of a company that believes corporations can change the world.
url: http://blog.nextjump.com/
githubAccount: NextJump
